kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jim-bridger.fullname" . }}
  labels:
    {{- include "jim-bridger.labels" . | nindent 4 }}
data:
  PRE_SHARED_SECRET: {{ (required "preSharedSecret is required" .Values.preSharedSecret) | b64enc | quote }}
  {{- with .Values.smtp }}
    {{- if .user }}
  SMTP_USER: {{ .user | b64enc | quote }}
    {{- end }}
    {{- if .password }}
  SMTP_PASSWORD: {{ .password | b64enc | quote }}
    {{- end }}
  {{- end }}