kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jim-bridger.fullname" . }}
  labels:
    {{- include "jim-bridger.labels" . | nindent 4 }}
data:
  PRE_SHARED_SECRET: {{ (required "preSharedSecret is required" .Values.preSharedSecret) | b64enc }}
{{/*  SMTP_USER: {{ (required "smtpUser is required" .Values.preSharedSecret) | b64enc }}*/}}
{{/*  SMTP_PASSWORD: {{ (required "smtpUser is required" .Values.preSharedSecret) | b64enc }}*/}}