### Test to me from Hey
POST https://jim-bridger.home.planetlauritsen.com/incoming
Authorization: Bearer {{api-key}}
Content-Type: text/plain

{{test-eml}}

### Test 400 bad request
POST https://jim-bridger.home.planetlauritsen.com/incoming
Authorization: Bearer {{api-key}}
Content-Type: text/plain

this is not a mail file

### Localhost Test to me from Hey
POST http://localhost:5000/incoming
Authorization: Bearer wooga
Content-Type: text/plain

{{test-eml}}
