name: Build and Push Docker Image

on:
  release:
    types:
      - created

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Log in to Docker Hub
      - name: Helm Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | helm registry login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io


      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{github.repository}}:${{ github.ref_name }}
          build-args: |
            DD_GIT_REPOSITORY_URL=${{ github.repositoryUrl }}
            DD_GIT_COMMIT_SHA=${{ github.sha }}

      # Package the Helm chart
      - name: Package Helm chart
        run: |
          rm -fr ./packaged/
          helm package ./helm --version ${{ github.ref_name }} --app-version ${{ github.ref_name }} -d packaged

      # Push Helm chart to Docker Hub
      - name: Push Helm chart to Docker Hub
        run: |
          CHART_NAME=${GITHUB_REPOSITORY##*/}
          helm push packaged/*.tgz oci://docker.io/cslauritsen